use_frameworks!

target 'XMGFMBase_Example' do
  pod 'XMGFMBase', :path => '../'

  target 'XMGFMBase_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
